/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PackageId = IDL.Nat;
export const BookingInput = IDL.Record({
  'addOn' : IDL.Variant({ 'videoOnly' : IDL.Null, 'videoAndVoice' : IDL.Null }),
  'clientName' : IDL.Text,
  'customInstructions' : IDL.Text,
  'clientEmail' : IDL.Text,
  'advanceAmount' : IDL.Nat,
  'clientPhone' : IDL.Text,
  'utrNumber' : IDL.Text,
  'packageId' : PackageId,
});
export const BookingId = IDL.Nat;
export const PortfolioEntryInput = IDL.Record({
  'title' : IDL.Text,
  'videoBlobId' : IDL.Opt(IDL.Text),
  'isPublished' : IDL.Bool,
  'thumbnailBlobId' : IDL.Opt(IDL.Text),
  'sortOrder' : IDL.Nat,
  'description' : IDL.Text,
  'embedUrl' : IDL.Opt(IDL.Text),
});
export const PortfolioEntryId = IDL.Nat;
export const ClientMessageId = IDL.Nat;
export const ClientMessage = IDL.Record({
  'id' : ClientMessageId,
  'bookingId' : BookingId,
  'createdAt' : IDL.Int,
  'messageText' : IDL.Text,
  'senderName' : IDL.Text,
});
export const PortfolioEntry = IDL.Record({
  'id' : PortfolioEntryId,
  'title' : IDL.Text,
  'videoBlobId' : IDL.Opt(IDL.Text),
  'isPublished' : IDL.Bool,
  'thumbnailBlobId' : IDL.Opt(IDL.Text),
  'sortOrder' : IDL.Nat,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'embedUrl' : IDL.Opt(IDL.Text),
});
export const BookingStatus = IDL.Variant({
  'pendingVerification' : IDL.Null,
  'completed' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : BookingId,
  'status' : BookingStatus,
  'addOn' : IDL.Variant({ 'videoOnly' : IDL.Null, 'videoAndVoice' : IDL.Null }),
  'clientName' : IDL.Text,
  'customInstructions' : IDL.Text,
  'createdAt' : IDL.Int,
  'clientEmail' : IDL.Text,
  'advanceAmount' : IDL.Nat,
  'clientPhone' : IDL.Text,
  'utrNumber' : IDL.Text,
  'adminNotes' : IDL.Opt(IDL.Text),
  'packageId' : PackageId,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Package = IDL.Record({
  'id' : PackageId,
  'videoOnlyPrice' : IDL.Nat,
  'tagline' : IDL.Opt(IDL.Text),
  'durationDescription' : IDL.Text,
  'name' : IDL.Text,
  'memberDetails' : IDL.Text,
  'isBestSeller' : IDL.Bool,
  'voiceAddonPrice' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBooking' : IDL.Func([BookingInput], [BookingId], []),
  'createPortfolioEntry' : IDL.Func(
      [PortfolioEntryInput],
      [PortfolioEntryId],
      [],
    ),
  'deletePortfolioEntry' : IDL.Func([PortfolioEntryId], [], []),
  'getAllClientMessages' : IDL.Func([], [IDL.Vec(ClientMessage)], ['query']),
  'getAllPortfolioEntries' : IDL.Func([], [IDL.Vec(PortfolioEntry)], ['query']),
  'getBookingById' : IDL.Func([BookingId], [IDL.Opt(Booking)], ['query']),
  'getBookings' : IDL.Func(
      [IDL.Opt(BookingStatus)],
      [IDL.Vec(Booking)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClientMessages' : IDL.Func(
      [BookingId],
      [IDL.Vec(ClientMessage)],
      ['query'],
    ),
  'getPackages' : IDL.Func([], [IDL.Vec(Package)], ['query']),
  'getPublishedPortfolioEntries' : IDL.Func(
      [],
      [IDL.Vec(PortfolioEntry)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedPortfolioEntries' : IDL.Func([], [], []),
  'sendClientMessage' : IDL.Func(
      [BookingId, IDL.Text, IDL.Text],
      [ClientMessageId],
      [],
    ),
  'updateBookingStatus' : IDL.Func(
      [BookingId, BookingStatus, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'updatePortfolioEntry' : IDL.Func(
      [PortfolioEntryId, PortfolioEntryInput],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PackageId = IDL.Nat;
  const BookingInput = IDL.Record({
    'addOn' : IDL.Variant({
      'videoOnly' : IDL.Null,
      'videoAndVoice' : IDL.Null,
    }),
    'clientName' : IDL.Text,
    'customInstructions' : IDL.Text,
    'clientEmail' : IDL.Text,
    'advanceAmount' : IDL.Nat,
    'clientPhone' : IDL.Text,
    'utrNumber' : IDL.Text,
    'packageId' : PackageId,
  });
  const BookingId = IDL.Nat;
  const PortfolioEntryInput = IDL.Record({
    'title' : IDL.Text,
    'videoBlobId' : IDL.Opt(IDL.Text),
    'isPublished' : IDL.Bool,
    'thumbnailBlobId' : IDL.Opt(IDL.Text),
    'sortOrder' : IDL.Nat,
    'description' : IDL.Text,
    'embedUrl' : IDL.Opt(IDL.Text),
  });
  const PortfolioEntryId = IDL.Nat;
  const ClientMessageId = IDL.Nat;
  const ClientMessage = IDL.Record({
    'id' : ClientMessageId,
    'bookingId' : BookingId,
    'createdAt' : IDL.Int,
    'messageText' : IDL.Text,
    'senderName' : IDL.Text,
  });
  const PortfolioEntry = IDL.Record({
    'id' : PortfolioEntryId,
    'title' : IDL.Text,
    'videoBlobId' : IDL.Opt(IDL.Text),
    'isPublished' : IDL.Bool,
    'thumbnailBlobId' : IDL.Opt(IDL.Text),
    'sortOrder' : IDL.Nat,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'embedUrl' : IDL.Opt(IDL.Text),
  });
  const BookingStatus = IDL.Variant({
    'pendingVerification' : IDL.Null,
    'completed' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : BookingId,
    'status' : BookingStatus,
    'addOn' : IDL.Variant({
      'videoOnly' : IDL.Null,
      'videoAndVoice' : IDL.Null,
    }),
    'clientName' : IDL.Text,
    'customInstructions' : IDL.Text,
    'createdAt' : IDL.Int,
    'clientEmail' : IDL.Text,
    'advanceAmount' : IDL.Nat,
    'clientPhone' : IDL.Text,
    'utrNumber' : IDL.Text,
    'adminNotes' : IDL.Opt(IDL.Text),
    'packageId' : PackageId,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Package = IDL.Record({
    'id' : PackageId,
    'videoOnlyPrice' : IDL.Nat,
    'tagline' : IDL.Opt(IDL.Text),
    'durationDescription' : IDL.Text,
    'name' : IDL.Text,
    'memberDetails' : IDL.Text,
    'isBestSeller' : IDL.Bool,
    'voiceAddonPrice' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBooking' : IDL.Func([BookingInput], [BookingId], []),
    'createPortfolioEntry' : IDL.Func(
        [PortfolioEntryInput],
        [PortfolioEntryId],
        [],
      ),
    'deletePortfolioEntry' : IDL.Func([PortfolioEntryId], [], []),
    'getAllClientMessages' : IDL.Func([], [IDL.Vec(ClientMessage)], ['query']),
    'getAllPortfolioEntries' : IDL.Func(
        [],
        [IDL.Vec(PortfolioEntry)],
        ['query'],
      ),
    'getBookingById' : IDL.Func([BookingId], [IDL.Opt(Booking)], ['query']),
    'getBookings' : IDL.Func(
        [IDL.Opt(BookingStatus)],
        [IDL.Vec(Booking)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClientMessages' : IDL.Func(
        [BookingId],
        [IDL.Vec(ClientMessage)],
        ['query'],
      ),
    'getPackages' : IDL.Func([], [IDL.Vec(Package)], ['query']),
    'getPublishedPortfolioEntries' : IDL.Func(
        [],
        [IDL.Vec(PortfolioEntry)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedPortfolioEntries' : IDL.Func([], [], []),
    'sendClientMessage' : IDL.Func(
        [BookingId, IDL.Text, IDL.Text],
        [ClientMessageId],
        [],
      ),
    'updateBookingStatus' : IDL.Func(
        [BookingId, BookingStatus, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'updatePortfolioEntry' : IDL.Func(
        [PortfolioEntryId, PortfolioEntryInput],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };