/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : BookingId,
  'status' : BookingStatus,
  'addOn' : { 'videoOnly' : null } |
    { 'videoAndVoice' : null },
  'clientName' : string,
  'customInstructions' : string,
  'createdAt' : bigint,
  'clientEmail' : string,
  'advanceAmount' : bigint,
  'clientPhone' : string,
  'utrNumber' : string,
  'adminNotes' : [] | [string],
  'packageId' : PackageId,
}
export type BookingId = bigint;
export interface BookingInput {
  'addOn' : { 'videoOnly' : null } |
    { 'videoAndVoice' : null },
  'clientName' : string,
  'customInstructions' : string,
  'clientEmail' : string,
  'advanceAmount' : bigint,
  'clientPhone' : string,
  'utrNumber' : string,
  'packageId' : PackageId,
}
export type BookingStatus = { 'pendingVerification' : null } |
  { 'completed' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface ClientMessage {
  'id' : ClientMessageId,
  'bookingId' : BookingId,
  'createdAt' : bigint,
  'messageText' : string,
  'senderName' : string,
}
export type ClientMessageId = bigint;
export interface Package {
  'id' : PackageId,
  'videoOnlyPrice' : bigint,
  'tagline' : [] | [string],
  'durationDescription' : string,
  'name' : string,
  'memberDetails' : string,
  'isBestSeller' : boolean,
  'voiceAddonPrice' : bigint,
}
export type PackageId = bigint;
export interface PortfolioEntry {
  'id' : PortfolioEntryId,
  'title' : string,
  'videoBlobId' : [] | [string],
  'isPublished' : boolean,
  'thumbnailBlobId' : [] | [string],
  'sortOrder' : bigint,
  'createdAt' : bigint,
  'description' : string,
  'embedUrl' : [] | [string],
}
export type PortfolioEntryId = bigint;
export interface PortfolioEntryInput {
  'title' : string,
  'videoBlobId' : [] | [string],
  'isPublished' : boolean,
  'thumbnailBlobId' : [] | [string],
  'sortOrder' : bigint,
  'description' : string,
  'embedUrl' : [] | [string],
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBooking' : ActorMethod<[BookingInput], BookingId>,
  'createPortfolioEntry' : ActorMethod<[PortfolioEntryInput], PortfolioEntryId>,
  'deletePortfolioEntry' : ActorMethod<[PortfolioEntryId], undefined>,
  'getAllClientMessages' : ActorMethod<[], Array<ClientMessage>>,
  'getAllPortfolioEntries' : ActorMethod<[], Array<PortfolioEntry>>,
  'getBookingById' : ActorMethod<[BookingId], [] | [Booking]>,
  'getBookings' : ActorMethod<[[] | [BookingStatus]], Array<Booking>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClientMessages' : ActorMethod<[BookingId], Array<ClientMessage>>,
  'getPackages' : ActorMethod<[], Array<Package>>,
  'getPublishedPortfolioEntries' : ActorMethod<[], Array<PortfolioEntry>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedPortfolioEntries' : ActorMethod<[], undefined>,
  'sendClientMessage' : ActorMethod<
    [BookingId, string, string],
    ClientMessageId
  >,
  'updateBookingStatus' : ActorMethod<
    [BookingId, BookingStatus, [] | [string]],
    undefined
  >,
  'updatePortfolioEntry' : ActorMethod<
    [PortfolioEntryId, PortfolioEntryInput],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];