/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type BookingId = bigint;
export interface PortfolioEntryInput {
    title: string;
    videoBlobId?: string;
    isPublished: boolean;
    thumbnailBlobId?: string;
    sortOrder: bigint;
    description: string;
    embedUrl?: string;
}
export interface BookingInput {
    addOn: Variant_videoOnly_videoAndVoice;
    clientName: string;
    customInstructions: string;
    clientEmail: string;
    advanceAmount: bigint;
    clientPhone: string;
    utrNumber: string;
    packageId: PackageId;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface PackageInput {
    videoOnlyPrice: bigint;
    tagline?: string;
    thumbnailBlobId?: string;
    sortOrder: bigint;
    durationDescription: string;
    name: string;
    memberDetails: string;
    isHidden: boolean;
    isBestSeller: boolean;
    voiceAddonPrice: bigint;
}
export interface ClientMessage {
    id: ClientMessageId;
    bookingId: BookingId;
    createdAt: bigint;
    messageText: string;
    senderName: string;
}
export interface Package {
    id: PackageId;
    videoOnlyPrice: bigint;
    tagline?: string;
    thumbnailBlobId?: string;
    sortOrder: bigint;
    durationDescription: string;
    name: string;
    memberDetails: string;
    isHidden: boolean;
    isBestSeller: boolean;
    voiceAddonPrice: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export type ClientMessageId = bigint;
export type PortfolioEntryId = bigint;
export type PackageId = bigint;
export interface Booking {
    id: BookingId;
    status: BookingStatus;
    addOn: Variant_videoOnly_videoAndVoice;
    clientName: string;
    customInstructions: string;
    createdAt: bigint;
    clientEmail: string;
    advanceAmount: bigint;
    clientPhone: string;
    utrNumber: string;
    adminNotes?: string;
    packageId: PackageId;
}
export interface PortfolioEntry {
    id: PortfolioEntryId;
    title: string;
    videoBlobId?: string;
    isPublished: boolean;
    thumbnailBlobId?: string;
    sortOrder: bigint;
    createdAt: bigint;
    description: string;
    embedUrl?: string;
}
export interface UserProfile {
    name: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum BookingStatus {
    pendingVerification = "pendingVerification",
    completed = "completed",
    approved = "approved",
    rejected = "rejected"
}
export enum ReorderDirection {
    up = "up",
    down = "down"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_videoOnly_videoAndVoice {
    videoOnly = "videoOnly",
    videoAndVoice = "videoAndVoice"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createBooking(input: BookingInput): Promise<BookingId>;
    createPackage(input: PackageInput): Promise<PackageId>;
    createPortfolioEntry(input: PortfolioEntryInput): Promise<PortfolioEntryId>;
    deletePackage(id: PackageId): Promise<void>;
    deletePortfolioEntry(id: PortfolioEntryId): Promise<void>;
    getAllClientMessages(): Promise<Array<ClientMessage>>;
    getAllPackages(): Promise<Array<Package>>;
    getAllPortfolioEntries(): Promise<Array<PortfolioEntry>>;
    getBookingById(id: BookingId): Promise<Booking | null>;
    getBookings(statusFilter: BookingStatus | null): Promise<Array<Booking>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getClientMessages(bookingId: BookingId): Promise<Array<ClientMessage>>;
    getPackages(): Promise<Array<Package>>;
    getPublishedPortfolioEntries(): Promise<Array<PortfolioEntry>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    reorderPortfolioEntry(id: PortfolioEntryId, direction: ReorderDirection): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    sendClientMessage(bookingId: BookingId, senderName: string, messageText: string): Promise<ClientMessageId>;
    updateBookingStatus(id: BookingId, status: BookingStatus, adminNotes: string | null): Promise<void>;
    updatePackage(id: PackageId, input: PackageInput): Promise<void>;
    updatePortfolioEntry(id: PortfolioEntryId, input: PortfolioEntryInput): Promise<void>;
}
import type { Booking as _Booking, BookingId as _BookingId, BookingInput as _BookingInput, BookingStatus as _BookingStatus, Package as _Package, PackageId as _PackageId, PackageInput as _PackageInput, PortfolioEntry as _PortfolioEntry, PortfolioEntryId as _PortfolioEntryId, PortfolioEntryInput as _PortfolioEntryInput, ReorderDirection as _ReorderDirection, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createBooking(arg0: BookingInput): Promise<BookingId> {
        if (this.processError) {
            try {
                const result = await this.actor.createBooking(to_candid_BookingInput_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBooking(to_candid_BookingInput_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createPackage(arg0: PackageInput): Promise<PackageId> {
        if (this.processError) {
            try {
                const result = await this.actor.createPackage(to_candid_PackageInput_n13(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPackage(to_candid_PackageInput_n13(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createPortfolioEntry(arg0: PortfolioEntryInput): Promise<PortfolioEntryId> {
        if (this.processError) {
            try {
                const result = await this.actor.createPortfolioEntry(to_candid_PortfolioEntryInput_n15(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPortfolioEntry(to_candid_PortfolioEntryInput_n15(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deletePackage(arg0: PackageId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePackage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePackage(arg0);
            return result;
        }
    }
    async deletePortfolioEntry(arg0: PortfolioEntryId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePortfolioEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePortfolioEntry(arg0);
            return result;
        }
    }
    async getAllClientMessages(): Promise<Array<ClientMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllClientMessages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllClientMessages();
            return result;
        }
    }
    async getAllPackages(): Promise<Array<Package>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPackages();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPackages();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPortfolioEntries(): Promise<Array<PortfolioEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPortfolioEntries();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPortfolioEntries();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingById(arg0: BookingId): Promise<Booking | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingById(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingById(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookings(arg0: BookingStatus | null): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookings(to_candid_opt_n30(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookings(to_candid_opt_n30(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClientMessages(arg0: BookingId): Promise<Array<ClientMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getClientMessages(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClientMessages(arg0);
            return result;
        }
    }
    async getPackages(): Promise<Array<Package>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPackages();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPackages();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublishedPortfolioEntries(): Promise<Array<PortfolioEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublishedPortfolioEntries();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublishedPortfolioEntries();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async reorderPortfolioEntry(arg0: PortfolioEntryId, arg1: ReorderDirection): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reorderPortfolioEntry(arg0, to_candid_ReorderDirection_n37(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reorderPortfolioEntry(arg0, to_candid_ReorderDirection_n37(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async sendClientMessage(arg0: BookingId, arg1: string, arg2: string): Promise<ClientMessageId> {
        if (this.processError) {
            try {
                const result = await this.actor.sendClientMessage(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendClientMessage(arg0, arg1, arg2);
            return result;
        }
    }
    async updateBookingStatus(arg0: BookingId, arg1: BookingStatus, arg2: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBookingStatus(arg0, to_candid_BookingStatus_n31(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n39(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBookingStatus(arg0, to_candid_BookingStatus_n31(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n39(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updatePackage(arg0: PackageId, arg1: PackageInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePackage(arg0, to_candid_PackageInput_n13(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePackage(arg0, to_candid_PackageInput_n13(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updatePortfolioEntry(arg0: PortfolioEntryId, arg1: PortfolioEntryInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePortfolioEntry(arg0, to_candid_PortfolioEntryInput_n15(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePortfolioEntry(arg0, to_candid_PortfolioEntryInput_n15(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_BookingStatus_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingStatus): BookingStatus {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_Booking_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Booking): Booking {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_Package_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Package): Package {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_PortfolioEntry_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PortfolioEntry): PortfolioEntry {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Booking]): Booking | null {
    return value.length === 0 ? null : from_candid_Booking_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PackageId;
    videoOnlyPrice: bigint;
    tagline: [] | [string];
    thumbnailBlobId: [] | [string];
    sortOrder: bigint;
    durationDescription: string;
    name: string;
    memberDetails: string;
    isHidden: boolean;
    isBestSeller: boolean;
    voiceAddonPrice: bigint;
}): {
    id: PackageId;
    videoOnlyPrice: bigint;
    tagline?: string;
    thumbnailBlobId?: string;
    sortOrder: bigint;
    durationDescription: string;
    name: string;
    memberDetails: string;
    isHidden: boolean;
    isBestSeller: boolean;
    voiceAddonPrice: bigint;
} {
    return {
        id: value.id,
        videoOnlyPrice: value.videoOnlyPrice,
        tagline: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.tagline)),
        thumbnailBlobId: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.thumbnailBlobId)),
        sortOrder: value.sortOrder,
        durationDescription: value.durationDescription,
        name: value.name,
        memberDetails: value.memberDetails,
        isHidden: value.isHidden,
        isBestSeller: value.isBestSeller,
        voiceAddonPrice: value.voiceAddonPrice
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PortfolioEntryId;
    title: string;
    videoBlobId: [] | [string];
    isPublished: boolean;
    thumbnailBlobId: [] | [string];
    sortOrder: bigint;
    createdAt: bigint;
    description: string;
    embedUrl: [] | [string];
}): {
    id: PortfolioEntryId;
    title: string;
    videoBlobId?: string;
    isPublished: boolean;
    thumbnailBlobId?: string;
    sortOrder: bigint;
    createdAt: bigint;
    description: string;
    embedUrl?: string;
} {
    return {
        id: value.id,
        title: value.title,
        videoBlobId: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.videoBlobId)),
        isPublished: value.isPublished,
        thumbnailBlobId: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.thumbnailBlobId)),
        sortOrder: value.sortOrder,
        createdAt: value.createdAt,
        description: value.description,
        embedUrl: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.embedUrl))
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _BookingId;
    status: _BookingStatus;
    addOn: {
        videoOnly: null;
    } | {
        videoAndVoice: null;
    };
    clientName: string;
    customInstructions: string;
    createdAt: bigint;
    clientEmail: string;
    advanceAmount: bigint;
    clientPhone: string;
    utrNumber: string;
    adminNotes: [] | [string];
    packageId: _PackageId;
}): {
    id: BookingId;
    status: BookingStatus;
    addOn: Variant_videoOnly_videoAndVoice;
    clientName: string;
    customInstructions: string;
    createdAt: bigint;
    clientEmail: string;
    advanceAmount: bigint;
    clientPhone: string;
    utrNumber: string;
    adminNotes?: string;
    packageId: PackageId;
} {
    return {
        id: value.id,
        status: from_candid_BookingStatus_n27(_uploadFile, _downloadFile, value.status),
        addOn: from_candid_variant_n29(_uploadFile, _downloadFile, value.addOn),
        clientName: value.clientName,
        customInstructions: value.customInstructions,
        createdAt: value.createdAt,
        clientEmail: value.clientEmail,
        advanceAmount: value.advanceAmount,
        clientPhone: value.clientPhone,
        utrNumber: value.utrNumber,
        adminNotes: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.adminNotes)),
        packageId: value.packageId
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pendingVerification: null;
} | {
    completed: null;
} | {
    approved: null;
} | {
    rejected: null;
}): BookingStatus {
    return "pendingVerification" in value ? BookingStatus.pendingVerification : "completed" in value ? BookingStatus.completed : "approved" in value ? BookingStatus.approved : "rejected" in value ? BookingStatus.rejected : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    videoOnly: null;
} | {
    videoAndVoice: null;
}): Variant_videoOnly_videoAndVoice {
    return "videoOnly" in value ? Variant_videoOnly_videoAndVoice.videoOnly : "videoAndVoice" in value ? Variant_videoOnly_videoAndVoice.videoAndVoice : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Package>): Array<Package> {
    return value.map((x)=>from_candid_Package_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PortfolioEntry>): Array<PortfolioEntry> {
    return value.map((x)=>from_candid_PortfolioEntry_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Booking>): Array<Booking> {
    return value.map((x)=>from_candid_Booking_n25(_uploadFile, _downloadFile, x));
}
function to_candid_BookingInput_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingInput): _BookingInput {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_BookingStatus_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): _BookingStatus {
    return to_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function to_candid_PackageInput_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PackageInput): _PackageInput {
    return to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_PortfolioEntryInput_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PortfolioEntryInput): _PortfolioEntryInput {
    return to_candid_record_n16(_uploadFile, _downloadFile, value);
}
function to_candid_ReorderDirection_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReorderDirection): _ReorderDirection {
    return to_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus | null): [] | [_BookingStatus] {
    return value === null ? candid_none() : candid_some(to_candid_BookingStatus_n31(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    addOn: Variant_videoOnly_videoAndVoice;
    clientName: string;
    customInstructions: string;
    clientEmail: string;
    advanceAmount: bigint;
    clientPhone: string;
    utrNumber: string;
    packageId: PackageId;
}): {
    addOn: {
        videoOnly: null;
    } | {
        videoAndVoice: null;
    };
    clientName: string;
    customInstructions: string;
    clientEmail: string;
    advanceAmount: bigint;
    clientPhone: string;
    utrNumber: string;
    packageId: _PackageId;
} {
    return {
        addOn: to_candid_variant_n12(_uploadFile, _downloadFile, value.addOn),
        clientName: value.clientName,
        customInstructions: value.customInstructions,
        clientEmail: value.clientEmail,
        advanceAmount: value.advanceAmount,
        clientPhone: value.clientPhone,
        utrNumber: value.utrNumber,
        packageId: value.packageId
    };
}
function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    videoOnlyPrice: bigint;
    tagline?: string;
    thumbnailBlobId?: string;
    sortOrder: bigint;
    durationDescription: string;
    name: string;
    memberDetails: string;
    isHidden: boolean;
    isBestSeller: boolean;
    voiceAddonPrice: bigint;
}): {
    videoOnlyPrice: bigint;
    tagline: [] | [string];
    thumbnailBlobId: [] | [string];
    sortOrder: bigint;
    durationDescription: string;
    name: string;
    memberDetails: string;
    isHidden: boolean;
    isBestSeller: boolean;
    voiceAddonPrice: bigint;
} {
    return {
        videoOnlyPrice: value.videoOnlyPrice,
        tagline: value.tagline ? candid_some(value.tagline) : candid_none(),
        thumbnailBlobId: value.thumbnailBlobId ? candid_some(value.thumbnailBlobId) : candid_none(),
        sortOrder: value.sortOrder,
        durationDescription: value.durationDescription,
        name: value.name,
        memberDetails: value.memberDetails,
        isHidden: value.isHidden,
        isBestSeller: value.isBestSeller,
        voiceAddonPrice: value.voiceAddonPrice
    };
}
function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    videoBlobId?: string;
    isPublished: boolean;
    thumbnailBlobId?: string;
    sortOrder: bigint;
    description: string;
    embedUrl?: string;
}): {
    title: string;
    videoBlobId: [] | [string];
    isPublished: boolean;
    thumbnailBlobId: [] | [string];
    sortOrder: bigint;
    description: string;
    embedUrl: [] | [string];
} {
    return {
        title: value.title,
        videoBlobId: value.videoBlobId ? candid_some(value.videoBlobId) : candid_none(),
        isPublished: value.isPublished,
        thumbnailBlobId: value.thumbnailBlobId ? candid_some(value.thumbnailBlobId) : candid_none(),
        sortOrder: value.sortOrder,
        description: value.description,
        embedUrl: value.embedUrl ? candid_some(value.embedUrl) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_videoOnly_videoAndVoice): {
    videoOnly: null;
} | {
    videoAndVoice: null;
} {
    return value == Variant_videoOnly_videoAndVoice.videoOnly ? {
        videoOnly: null
    } : value == Variant_videoOnly_videoAndVoice.videoAndVoice ? {
        videoAndVoice: null
    } : value;
}
function to_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): {
    pendingVerification: null;
} | {
    completed: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == BookingStatus.pendingVerification ? {
        pendingVerification: null
    } : value == BookingStatus.completed ? {
        completed: null
    } : value == BookingStatus.approved ? {
        approved: null
    } : value == BookingStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReorderDirection): {
    up: null;
} | {
    down: null;
} {
    return value == ReorderDirection.up ? {
        up: null
    } : value == ReorderDirection.down ? {
        down: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
